/**
 * Tunisian E-Commerce Network Extractor (Shadow Network Engine)
 * Extracts Tunisian phone numbers, WhatsApp order links, Meta Pixel IDs, and store platform.
 * $0 LLM Cost — 100% fast deterministic regex and HTML parsing.
 */

// Known phantom artifact numbers generated by CSS coordinates or SVG path floats
export const PHANTOM_PHONE_BLACKLIST = new Set<string>([
  "21624277023", // CSS oklch float artifact
  "21659817721", // CSS oklch float artifact
  "21641397728", // SVG path coordinate artifact
  "21623622354", // SVG path coordinate artifact
  "21692602474", // SVG path coordinate artifact
  "21638504379", // SVG path coordinate artifact
  "21620202020", // Theme placeholder
  "21622222222", // Theme placeholder
]);

/**
 * Validates that an 8-digit Tunisian number is not a repetitive or placeholder dummy number.
 */
export function isPlaceholderOrDummyPhone(phone: string): boolean {
  const digits = phone.startsWith("216") ? phone.slice(3) : phone;
  if (digits.length !== 8) return true;
  // All same digit (e.g. 22222222, 99999999)
  if (/^(\d)\1{7}$/.test(digits)) return true;
  // Repeating 2-digit pairs (e.g. 20202020, 21212121)
  if (/^(\d{2})\1{3}$/.test(digits)) return true;
  // Repeating 4-digit halves (e.g. 21602160)
  if (/^(\d{4})\1$/.test(digits)) return true;
  // Sequential ascending / descending
  if (digits === "12345678" || digits === "87654321" || digits === "23456789") return true;
  // Obvious dummy zeros
  if (digits === "20000000" || digits === "21600000" || digits === "90000000") return true;
  return false;
}

/**
 * Strips SVG tags, style sheets, path coordinates, and data URLs so numeric coordinates
 * cannot be mistakenly matched as phone numbers.
 */
export function sanitizeHtmlForPhoneExtraction(content?: string | null): string {
  if (!content) return "";
  return content
    // Remove svg tags and all nested path data
    .replace(/<svg\b[^>]*>[\s\S]*?<\/svg>/gi, " ")
    // Remove style tags and all CSS rules
    .replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi, " ")
    // Remove path/point attributes
    .replace(/\b(?:d|points)\s*=\s*["'][^"']*["']/gi, " ")
    // Remove base64 or data URLs
    .replace(/data:image\/[^"'\s]+/gi, " ")
    // Remove script tags except structured ld+json
    .replace(/<script\b(?![^>]*application\/ld\+json)[^>]*>[\s\S]*?<\/script>/gi, " ")
    // Remove HTML comments
    .replace(/<!--[\s\S]*?-->/g, " ");
}

/**
 * Normalizes and extracts Tunisian phone numbers (+216 2X/3X/4X/5X/7X/9X...).
 * Standardizes to "216XXXXXXXX" format.
 */
export function extractTunisianPhoneNumbers(content?: string | null): string[] {
  if (!content) return [];

  const sanitized = sanitizeHtmlForPhoneExtraction(content);
  const numbers = new Set<string>();

  const addValidPhone = (rawDigits?: string | null) => {
    if (!rawDigits) return;
    const clean = rawDigits.replace(/\D/g, "");
    const local = clean.startsWith("216") ? clean.slice(3) : clean;
    if (local.length !== 8) return;
    // Validate Tunisian prefixes: 2, 3, 4, 5, 7, 9
    if (!/^[234579]\d{7}$/.test(local)) return;
    const full = `216${local}`;
    if (PHANTOM_PHONE_BLACKLIST.has(full)) return;
    if (isPlaceholderOrDummyPhone(local)) return;
    numbers.add(full);
  };

  // 1. Direct tel: links (Highest confidence)
  // href="tel:+216 25 930 780" or href="tel:25930780"
  const telLinkRegex = /href=["']tel:\s*(?:\+?216)?\s*([234579][\d\s.-]{7,15})["']/gi;
  let match;
  while ((match = telLinkRegex.exec(content)) !== null) {
    addValidPhone(match[1]);
  }

  // 2. WhatsApp links (Direct wa.me or api.whatsapp.com)
  const waNumbers = extractWhatsAppNumbers(content);
  waNumbers.forEach((num) => addValidPhone(num));

  // 3. Structured JSON-LD / schema.org telephone
  const jsonLdPhoneRegex = /["']telephone["']\s*:\s*["']([^"']+)["']/gi;
  while ((match = jsonLdPhoneRegex.exec(content)) !== null) {
    addValidPhone(match[1]);
  }

  // 4. Tunisian Country-Coded format in text (+216 or 00216 or (216) or 216)
  // Negative lookbehind and lookahead to prevent matching decimals or concatenated IDs
  const countryCodedRegex = /(?<![\d.a-zA-Z%])(?:\+|00|\b)(?:216|\(216\))\s*[-.\s]?([234579]\d(?:[-.\s]?\d){6})(?![\d.a-zA-Z])/gi;
  while ((match = countryCodedRegex.exec(sanitized)) !== null) {
    addValidPhone(match[1]);
  }

  // 5. Standalone 8-digit format with spaces or hyphens (NEVER standalone dots without +216)
  // Examples: 25 930 780 or 25-930-780
  const standaloneRegex = /(?<![\d.a-zA-Z%])([234579]\d)[-\s]+(\d{3})[-\s]+(\d{3})(?![\d.a-zA-Z])/g;
  while ((match = standaloneRegex.exec(sanitized)) !== null) {
    addValidPhone(`${match[1]}${match[2]}${match[3]}`);
  }

  // 6. Contact context with 8 continuous digits (e.g. "Tél: 25930780", "Infoline: 55900353")
  const contextRegex = /(?:t[ée]l[ée]?phone|infoline|service client|gsm|contact|appelez(?:-nous)?|commande)\s*[:#-]?\s*([234579]\d{7})(?![\d.a-zA-Z])/gi;
  while ((match = contextRegex.exec(sanitized)) !== null) {
    addValidPhone(match[1]);
  }

  return Array.from(numbers);
}


/**
 * Extracts WhatsApp phone numbers from direct wa.me or api.whatsapp.com links.
 */
export function extractWhatsAppNumbers(content?: string | null): string[] {
  if (!content) return [];

  const numbers = new Set<string>();

  // Pattern: wa.me/216XXXXXXXX, wa.me/+216XXXXXXXX, api.whatsapp.com/send?phone=216XXXXXXXX, etc.
  const waRegex = /(?:wa\.me\/|api\.whatsapp\.com\/send\/?\?phone=|whatsapp:\/\/send\?phone=)(?:\+?216)?([234579]\d{7})/gi;
  let match;
  while ((match = waRegex.exec(content)) !== null) {
    numbers.add(`216${match[1]}`);
  }

  return Array.from(numbers);
}

/**
 * Extracts Meta / Facebook Pixel IDs from HTML / JavaScript tags.
 */
export function extractMetaPixelIds(content?: string | null): string[] {
  if (!content) return [];

  const pixelIds = new Set<string>();

  // Pattern 1: fbq('init', '123456789012345') or fbq("init", "123456789012345")
  const fbqRegex = /fbq\(\s*['"]init['"]\s*,\s*['"](\d{12,18})['"]/gi;
  let match;
  while ((match = fbqRegex.exec(content)) !== null) {
    pixelIds.add(match[1]);
  }

  // Pattern 2: connect.facebook.net/.../fbevents.js or tr?id=123456789012345
  const trRegex = /(?:connect\.facebook\.net|facebook\.com\/tr)\?[^'"]*id=(\d{12,18})/gi;
  while ((match = trRegex.exec(content)) !== null) {
    pixelIds.add(match[1]);
  }

  // Pattern 3: Common JSON pixel configs, e.g. "pixel_id": "123456789012345" or "pixelId": 123456789012345
  const jsonPixelRegex = /["']pixel[_-]?id["']\s*:\s*["']?(\d{12,18})["']?/gi;
  while ((match = jsonPixelRegex.exec(content)) !== null) {
    pixelIds.add(match[1]);
  }

  return Array.from(pixelIds);
}

/**
 * Classifies the store e-commerce engine (YouCan, WooCommerce, Shopify, Custom COD, etc.).
 */
export function detectStorePlatform(
  html?: string | null,
  url?: string | null
): "youcan" | "woocommerce" | "shopify" | "custom_cod" | "stocki" | "other" {
  const content = (html || "").toLowerCase();
  const rawUrl = (url || "").toLowerCase();

  // 1. YouCan (Huge in Tunisia & North Africa COD)
  if (
    content.includes("youcan.shop") ||
    content.includes("assets.youcan.shop") ||
    content.includes("cdn.youcan.shop") ||
    content.includes("youcan-") ||
    rawUrl.includes("youcan.store") ||
    rawUrl.includes("youcan.shop")
  ) {
    return "youcan";
  }

  // 2. WooCommerce / WordPress
  if (
    content.includes("wp-content") ||
    content.includes("wp-includes") ||
    content.includes("woocommerce") ||
    content.includes("wc-ajax")
  ) {
    return "woocommerce";
  }

  // 3. Shopify
  if (
    content.includes("cdn.shopify.com") ||
    content.includes("shopify.shop") ||
    content.includes("myshopify.com") ||
    rawUrl.includes("myshopify.com")
  ) {
    return "shopify";
  }

  // 3b. Stocki Platform (Tunisian COD Platform)
  if (
    content.includes("stocki.tn") ||
    content.includes("stocki.co") ||
    rawUrl.includes("stocki.tn") ||
    rawUrl.includes("stocki.co")
  ) {
    return "stocki";
  }

  // 4. Custom COD Landing Page (Funnelish / Leadpages / Custom PHP with COD form)
  if (
    content.includes("gouvernorat") ||
    content.includes("délégation") ||
    content.includes("delegation") ||
    content.includes("nom et prénom") ||
    content.includes("adresse de livraison") ||
    content.includes("commander maintenant") ||
    content.includes("الدفع عند الاستلام") ||
    content.includes("توصيل")
  ) {
    return "custom_cod";
  }

  return "other";
}

/**
 * Formats a normalized "216XXXXXXXX" number into human-friendly "+216 XX XXX XXX" with telecom operator info.
 */
export function formatTunisianPhone(phone: string): {
  formatted: string;
  operator: "Ooredoo" | "Orange" | "Tunisie Telecom" | "Fixe" | "Unknown";
} {
  const clean = phone.replace(/\D/g, "");
  const localDigits = clean.startsWith("216") ? clean.slice(3) : clean;

  if (localDigits.length !== 8) {
    return { formatted: phone, operator: "Unknown" };
  }

  const prefix = localDigits[0];
  let operator: "Ooredoo" | "Orange" | "Tunisie Telecom" | "Fixe" | "Unknown" = "Unknown";

  if (prefix === "2" || prefix === "9") {
    // 2X = Ooredoo, 9X = Tunisie Telecom
    operator = prefix === "2" ? "Ooredoo" : "Tunisie Telecom";
  } else if (prefix === "5") {
    operator = "Orange";
  } else if (prefix === "7" || prefix === "3") {
    operator = "Fixe";
  } else if (prefix === "4") {
    operator = "Tunisie Telecom";
  }

  const formatted = `+216 ${localDigits.slice(0, 2)} ${localDigits.slice(2, 5)} ${localDigits.slice(5)}`;
  return { formatted, operator };
}

/**
 * Detects delivery/shipping policy (Livraison gratuite, 7 DT, 8 DT, Gratuite dès 2 pièces, etc.)
 */
export function extractDeliveryInfo(
  htmlOrText?: string | null,
  extractedDelivery?: string | null,
  allOffers?: Array<{ tier_name?: string; tierName?: string; price?: string }> | null
): { isFree: boolean; label: string; rawCost?: string; isConditional?: boolean } {
  // Check form hidden inputs first (e.g. name="frais" value="7.000")
  if (htmlOrText) {
    const formDeliveryMatch =
      htmlOrText.match(/<input[^>]+name=["'](?:frais|frais_livraison|shipping_cost|frais_de_port)["'][^>]+value=["']([^"']+)["']/i) ||
      htmlOrText.match(/<input[^>]+value=["']([^"']+)["'][^>]+name=["'](?:frais|frais_livraison|shipping_cost|frais_de_port)["']/i);
    if (formDeliveryMatch && formDeliveryMatch[1]) {
      const cleaned = formDeliveryMatch[1].replace(/[^0-9.,]/g, "").trim();
      const val = parseFloat(cleaned.replace(",", "."));
      if (!isNaN(val) && val > 0) {
        const cost = val >= 1000 ? Math.round(val / 1000) : val;
        return {
          isFree: false,
          label: `Livraison: ${cost} DT`,
          rawCost: `${cost} DT`,
        };
      }
    }
  }

  const content = (htmlOrText || "").toLowerCase();

  // 1. Check for explicit checkout paid shipping amounts first (e.g. "Shipping: 7.00 DT", "Frais de livraison: 7 DT")
  const paidMatch =
    content.match(/(?:shipping|frais de livraison|frais livraison|livraison|توصيل|مصاريف الشحن)\s*[:=\s]\s*([1-9][0-9]*(?:\.[0-9]+)?\s*(?:dt|tnd|dinar|dinars|د\.ت|دت|د))/i) ||
    content.match(/([1-9][0-9]*(?:\.[0-9]{2})?)\s*(?:dt|tnd)\s*(?:de livraison|pour la livraison|frais)/i);

  // 2. Check for Conditional Free Delivery (e.g. "Livraison gratuite à partir de 2", "اشتري زوز توصيل مجاني")
  const hasConditionalFree =
    content.includes("livraison gratuite à partir de") ||
    content.includes("livraison gratuite des") ||
    content.includes("livraison gratuite dès") ||
    content.includes("توصيل مجاني عند شراء") ||
    content.includes("توصيل مجاني بداية من") ||
    content.includes("اشتري زوز توصيل مجاني") ||
    content.includes("اشتري 2 توصيل مجاني") ||
    content.includes("اشري 2 توصيل مجاني") ||
    content.includes("اشري زوز توصيل مجاني") ||
    (content.includes("pack 2") && content.includes("gratuit")) ||
    (allOffers &&
      Array.isArray(allOffers) &&
      allOffers.some((o, idx) => {
        const name = (o.tier_name || o.tierName || "").toLowerCase();
        return (
          idx > 0 &&
          (name.includes("مجاني") ||
            name.includes("gratuit") ||
            name.includes("free") ||
            name.includes("بلاش"))
        );
      }));

  // If there's an explicit paid delivery amount
  if (paidMatch) {
    const rawCost = paidMatch[1].toUpperCase().trim();
    if (hasConditionalFree) {
      return {
        isFree: false,
        isConditional: true,
        label: `Livraison: ${rawCost} (Gratuite dès 2 pcs)`,
        rawCost,
      };
    }
    return {
      isFree: false,
      label: `Livraison: ${rawCost}`,
      rawCost,
    };
  }

  // If conditional free delivery detected (e.g. Buy 2 get free delivery) but single item has standard delivery
  if (hasConditionalFree) {
    return {
      isFree: false,
      isConditional: true,
      label: "Livraison: 7 DT (Gratuite dès 2 pcs)",
      rawCost: "7 DT",
    };
  }

  // If Firecrawl explicitly extracted a delivery policy
  if (
    extractedDelivery &&
    extractedDelivery.trim().length > 0 &&
    extractedDelivery.toLowerCase() !== "non spécifiée" &&
    extractedDelivery.toLowerCase() !== "unspecified"
  ) {
    const lower = extractedDelivery.toLowerCase();
    const isFree =
      lower.includes("gratuit") ||
      lower.includes("free") ||
      lower.includes("مجاني") ||
      lower.includes("0 dt") ||
      lower.includes("0dt") ||
      lower.includes("بلاش");

    if (isFree && !hasConditionalFree) {
      return {
        isFree: true,
        label: "Livraison Gratuite",
        rawCost: "0 DT",
      };
    }

    if (!isFree) {
      return {
        isFree: false,
        label: extractedDelivery.startsWith("Livraison")
          ? extractedDelivery
          : `Livraison: ${extractedDelivery}`,
        rawCost: extractedDelivery,
      };
    }
  }

  // 3. Check for genuine Unconditional Free Delivery on single item
  const hasUnconditionalFree =
    (content.includes("livraison gratuite") ||
      content.includes("livraison offerte") ||
      content.includes("توصيل مجاني") ||
      content.includes("شحن مجاني") ||
      content.includes("free shipping") ||
      content.includes("livraison 0 dt") ||
      content.includes("livraison 0dt") ||
      content.includes("توصيل بلاش")) &&
    !hasConditionalFree;

  if (hasUnconditionalFree) {
    return {
      isFree: true,
      label: "Livraison Gratuite",
      rawCost: "0 DT",
    };
  }

  // 4. Default for Tunisian COD
  return {
    isFree: false,
    label: "Livraison: 7 DT",
    rawCost: "7 DT",
  };
}
